default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: novos_recomecos_development
  username: <%= ENV['DB_USERNAME'] || "novosrecomecos" %>
  password: <%= ENV['DB_PASSWORD'] || "recomecos112358132134589" %>
  host: <%= ENV['DB_HOST'] || "localhost" %>

test:
  <<: *default
  database: novos_recomecos_test
  username: <%= ENV['DB_USERNAME'] || "novosrecomecos" %>
  password: <%= ENV['DB_PASSWORD'] || "recomecos112358132134589" %>
  host: <%= ENV['DB_HOST'] || "localhost" %>

production:
  <<: *default
  database: <%= ENV['DB_NAME'] || "novos_recomecos_production" %>
  username: <%= ENV['DB_USERNAME'] || "novosrecomecos" %>
  password: <%= ENV['DB_PASSWORD'] || "recomecos112358132134589" %>
  host: <%= ENV['DB_HOST'] || "db" %>
